######### Istio Operator-less (istioCore) Overrides #############
networkPolicies:
  enabled: true

istio:
  enabled: false

istioOperator:
  enabled: false
  
istioCRDs:
  enabled: true

istiod:
  enabled: true

istioGateway:
  enabled: true

######### Additional Overrides ###########

wrapper:
  git:
    branch: add-function
    tag: null

packages:
  # This will be used as the namespace for the install, as well as the name of the helm release. If this is changed, the destination service (below) needs to also be changed.
  jira:
    enabled: true
    git:
      repo: https://repo1.dso.mil/big-bang/product/community/jira
      # # It is recommended to update this to the latest bb tag
      path: chart
      branch: main
      tag: null
    dependsOn:
      - name: istiod
        namespace: bigbang
    # Disabling this will bypass creating the istio VirtualService and NetworkPolicies.
    wrapper:
      enabled: true
    # This section is ignored if `wrapper.enabled`, above, is false. In this case, creation of an ingress for web access is left as an exercise for the reader.
    istio:
      enabled: true
      injection: "enabled"
      hosts:
        - names:
            - "jira"
          gateways:
            - "public-ingressgateway"
          destination:
            port: 8080
    # Anything in this section is passed to the jira chart directly; this allows all of your bigbang configuration to be in a single place.
    values:
      jira:
        service:
          port: 8080


  # This will be used as the namespace for the install, as well as the name of the helm release. If this is changed, the destination service (below) needs to also be changed.
  confluence:
    enabled: true
    git:
      repo: https://repo1.dso.mil/big-bang/product/community/confluence
      # # It is recommended to update this to the latest bb tag
      path: chart
      branch: main
      tag: null
    dependsOn:
      - name: istiod
        namespace: bigbang
    # Disabling this will bypass creating the istio VirtualService and NetworkPolicies.
    wrapper:
      enabled: true
    # This section is ignored if `wrapper.enabled`, above, is false. In this case, creation of an ingress for web access is left as an exercise for the reader.
    istio:
      enabled: true
      injection: "enabled"
      hosts:
        - names:
            - "confluence"
          gateways:
            - "public-ingressgateway"
          destination:
            port: 8090
    # Anything in this section is passed to the confluence chart directly; this allows all of your bigbang configuration to be in a single place.
    values:
      confluence:
        service:
          port: 8090
